[default]

[debug]
features = "debug"

[fn_res]
features = "fn_res"

[debug_fn_res]
features = "debug fn_res"

[fn_meta]
features = "debug fn_res fn_meta"

[report]
out = ["Html", "Xml"]
output-dir = "target/tarpaulin"
