[default]

[debug]
features = "debug"

[fn_res]
features = "fn_res"

[fn_res_mut]
features = "fn_res fn_res_mut"

[fn_res_once]
features = "fn_res fn_res_mut fn_res_once"

[debug_fn_res]
features = "debug fn_res"

[high_arg_count]
features = "debug fn_res fn_res_mut fn_res_once high_arg_count"

[report]
out = ["Html", "Xml"]
output-dir = "target/tarpaulin"
